apiVersion: v1
kind: Service
metadata:
  name: movies-recommender-service
  labels:
    app: movies-recommender
spec:
  type: LoadBalancer
  selector:
    app: movies-recommender
  ports:
    - port: 80           # Puerto externo (LB) por donde se expondrá el servicio
      targetPort: 5011   # Redirige al puerto 5011 dentro del contenedor
      protocol: TCP