apiVersion: v1
kind: Service
metadata:
  name: movies-recommender-service
  labels:
    app: movies-recommender
spec:
  type: LoadBalancer
  selector:
    app: movies-recommender
  ports:
    - port: 80          # Puerto externo (LB) por donde se expondrá el servicio
      targetPort: 5000  # Puerto del contenedor al que redirige el LB
      protocol: TCP
